services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codd_queue_bot
    restart: always
    depends_on:
      - redis
    volumes:
      - ./bot:/app/bot
      - ./database:/app/database
      - ./logs:/app/logs
    env_file:
      - .env
    command: python -m bot
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  redis:
    image: redis:7-alpine
    container_name: codd_queue_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data: