services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codd_queue_bot
    restart: always
    volumes:
      - ./bot:/app/bot
      - ./database:/app/database
    env_file:
      - .env
    command: python -m bot