services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codd_queue_bot
    restart: always
    depends_on:
      - redis
    volumes:
      - ./bot:/app/bot:ro
      - db_data:/app/database
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE:-Europe/Moscow}
    user: root
    entrypoint: ["/bin/bash", "/docker-entrypoint.sh"]
    command: ["python", "-m", "bot"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  redis:
    image: redis:7-alpine
    container_name: codd_queue_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data:
  db_data: